name: shell-actions
run-name: ${{ github.action }} shell-actions
on: [push]
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
            node-version: '14'
      - run: echo "Hello"