name: shell-actions
run-name: ${{ github.actor }} shell-actions
on: [push]
jobs:
  write-a-hello-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
  write-a-goodbye-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GoodBye"
